services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # 开发模式：禁用 CSP、便于本地联调
      NODE_ENV: development
      DISABLE_CSP: "true"
      RUN_MIGRATIONS: "false"
