import { defineConfig } from 'vitest/config';

// Repo has a mix of `node:test` and `vitest` test files.
// This config scopes Vitest to the Vitest-based runtime tests so `npx vitest run tests/agents/runtime`
// doesn't attempt to execute `node:test` suites (which would fail under Vitest).
export default defineConfig({
  test: {
    include: [
      'tests/api/**/*.test.js',
      'tests/chatbot/**/*.test.js',
      'tests/core/**/*.test.js',
      'tests/history/**/*.test.js',
      'tests/processing/**/*.test.js',
      'tests/agents/core/**/*.test.js',
      'tests/agents/runtime/analysis.test.js',
      'tests/agents/runtime/compression.test.js',
      'tests/agents/runtime/core.test.js',
      'tests/agents/runtime/di-defaults-smoke.test.js',
      'tests/agents/runtime/di-singletons.test.js',
      'tests/agents/runtime/file-lock.test.js',
      'tests/agents/runtime/injection-scanner.test.js',
      'tests/agents/runtime/memory.test.js',
      'tests/agents/runtime/telemetry.test.js',
      'tests/agents/runtime/adaptive-token-counter.test.js',
      'tests/agents/runtime/token-tracker.test.js',
      'tests/agents/runtime/task-tool-di.test.js',
      'tests/ppt/ui-v2/event-bus.test.js',
      'tests/ppt/ui-v2/state-store.test.js',
      'tests/ppt/ui-v2/state-store.events.test.js',
      'tests/ppt/dsl/serialize.test.js',
      'tests/ppt/workflow/workflow-states.test.js',
      'tests/ppt/workflow/unified-state-mapping.vitest.test.js',
      'tests/ppt/core/math-converter.test.js',
      'tests/ppt/core/health-check.test.js',
      'tests/ppt/core/slide-constants.test.js',
      'tests/ppt/storage/checkpoint-manager.test.js',
      'tests/ui/**/*.test.js',
      'tests/storage/**/*.test.js',
      'tests/annotations/**/*.test.js',
      'tests/shared/**/*.test.js',
      'tests/utils/**/*.test.js',
    ],
    coverage: {
      provider: 'v8',
      include: [
        'js/agents/core/lamport-clock.js',
        'js/agents/runtime/tools/TaskTool.js',
        'js/agents/runtime/di/defaults.js',
        'js/agents/runtime/di/global-container.js',
        'js/agents/sdk/injection-scanner.js',
        'js/agents/runtime/telemetry/token-tracker.js',
        'js/agents/shared/tokenizers/adaptive-token-counter.js',
        'js/agents/vfs/file-lock.js',
      ],
      reporter: ['text'],
      statements: 90,
      functions: 90,
      branches: 85,
      lines: 90,
    },
  },
});
