import { defineConfig } from 'vitest/config';
import fs from 'node:fs';
import path from 'node:path';

// Workaround: @vitest/coverage-v8 may assume `coverage/.tmp` exists.
// Create it unconditionally (best-effort) to avoid racey ENOENT failures.
try {
  fs.mkdirSync(path.join(process.cwd(), 'coverage', '.tmp'), { recursive: true });
} catch {
  // Best-effort: tests can still run without coverage output.
}

// Repo has a mix of `node:test` and `vitest` test files.
// This config scopes Vitest to the Vitest-based runtime tests so `npx vitest run tests/agents/runtime`
// doesn't attempt to execute `node:test` suites (which would fail under Vitest).
export default defineConfig({
  test: {
    include: [
      'tests/app/**/*.test.js',
      'tests/api/**/*.test.js',
      'tests/chatbot/**/*.test.js',
      'tests/core/**/*.test.js',
      'tests/history/**/*.test.js',
      'tests/processing/**/*.test.js',
      'tests/agents/core/**/*.test.js',
      'tests/agents/ingest/**/*.vitest.test.js',
      'tests/agents/retrieval/**/*.vitest.test.js',
      'tests/agents/shared/utils/**/*.test.js',
      'tests/agents/vfs/**/*.test.js',
      'tests/agents/plugins/**/*.test.js',
      'tests/agents/skills/**/*.test.js',
      'tests/agents/storage/**/*.test.js',
      'tests/agents/mcp/**/*.test.js',
      'tests/agents/runtime/analysis.test.js',
      'tests/agents/runtime/compression.test.js',
      'tests/agents/runtime/compression/cicada-compressor.test.js',
      'tests/agents/runtime/compression/context-predictor.test.js',
      'tests/agents/runtime/compression/adaptive-zone-manager.test.js',
      'tests/agents/runtime/compression/proactive-compressor.test.js',
      'tests/agents/runtime/core.test.js',
      'tests/agents/runtime/core/**/*.test.js',
      'tests/agents/runtime/di-defaults-smoke.test.js',
      'tests/agents/runtime/di-singletons.test.js',
      'tests/agents/runtime/file-lock.test.js',
      'tests/agents/runtime/injection-scanner.test.js',
      'tests/agents/runtime/memory.test.js',
      'tests/agents/runtime/memory/memory-store.test.js',
      'tests/agents/runtime/telemetry.test.js',
      'tests/agents/runtime/adaptive-token-counter.test.js',
      'tests/agents/runtime/token-tracker.test.js',
      'tests/agents/runtime/task-tool-di.test.js',
      'tests/agents/runtime/hooks/hook-event.test.js',
      'tests/agents/runtime/hooks/hook-registry.test.js',
      'tests/agents/runtime/hooks/hooks-config-loader.test.js',
      'tests/agents/sdk/agent-builder.test.js',
      'tests/agents/sdk/agent-factory.test.js',
      'tests/agents/llm/**/*.vitest.test.js',
      'tests/ppt/ui-v2/event-bus.test.js',
      'tests/ppt/ui-v2/state-store.test.js',
      'tests/ppt/dsl/serialize.test.js',
      'tests/ppt/workflow/workflow-states.test.js',
      'tests/ppt/core/math-converter.test.js',
      'tests/ppt/core/health-check.test.js',
      'tests/ui/**/*.test.js',
      'tests/storage/**/*.test.js',
      'tests/annotations/**/*.test.js',
      'tests/shared/**/*.test.js',
      'tests/utils/**/*.test.js',
    ],
    coverage: {
      provider: 'v8',
      // Workaround: with v8 coverage + parallel workers, `clean: true` can race and remove
      // the temporary coverage directory while other workers are still writing.
      clean: false,
      include: [
        'js/agents/retrieval/bm25.js',
        'js/agents/retrieval/vector-search.js',
        'js/agents/retrieval/hybrid-retrieval.js',
        'js/agents/retrieval/mmr.js',
        'js/agents/core/lamport-clock.js',
        'js/agents/runtime/tools/TaskTool.js',
        'js/agents/runtime/di/defaults.js',
        'js/agents/runtime/di/global-container.js',
        'js/agents/runtime/memory/memory-store.js',
        'js/agents/runtime/memory/memory-store.impl.js',
        'js/agents/runtime/hooks/hook-registry.js',
        'js/agents/runtime/compression/coordinator.js',
        'js/agents/runtime/compression/cicada-compressor.js',
        'js/agents/runtime/core/tool-registry.js',
        'js/agents/runtime/core/message-manager.js',
        'js/agents/runtime/core/status-controller.js',
        'js/agents/plugins/compression/watchdog.js',
        'js/agents/sdk/AgentBuilder.js',
        'js/agents/sdk/agent-factory.js',
        'js/agents/sdk/injection-scanner.js',
        'js/agents/runtime/telemetry/token-tracker.js',
        'js/agents/shared/tokenizers/adaptive-token-counter.js',
        'js/agents/shared/utils/circuit-breaker.js',
        'js/agents/shared/utils/cancellation.js',
        'js/agents/shared/utils/deque.js',
        'js/agents/shared/utils/lru-cache.js',
        'js/agents/shared/utils/schema-validator.js',
        'js/agents/vfs/path.js',
        'js/agents/vfs/glob.js',
        'js/agents/vfs/vfs.memory.js',
        'js/agents/vfs/file-lock.js',
        'js/agents/vfs/operations.js',
        'js/agents/vfs/checkpoints.js',
        'js/agents/vfs/delta-sync.js',
        'js/agents/ingest/adapters/pdf.js',
        'js/agents/ingest/adapters/docx.js',
        'js/agents/ingest/adapters/markdown.js',
        'js/agents/mcp/mcp-client.js',
        'js/agents/mcp/mcp-nexus-provider.js',
        'js/agents/mcp/sse.js',
        'js/agents/shared/contracts/tool-result.js',
        'js/agents/llm/model-router.js',
        'js/agents/llm/rate-limit.js',
        'js/agents/llm/overflow-recovery.js',
        'js/agents/storage/run-store.js',
        'js/agents/storage/run-exporter.js',
        'js/agents/storage/artifact-manager.js',
        'js/agents/skills/loader.js',
        'js/agents/skills/loader.node.js',
        'js/agents/skills/user-store.js',
        'js/agents/core/sandbox/skill-executor.js',
      ],
      reporter: ['text'],
      statements: 90,
      functions: 90,
      branches: 85,
      lines: 90,
    },
  },
});
