/**
 * @paper-burner/agents stages aggregate entry
 *
 * Canonical import surface for built-in stages.
 */

export * from './deepsearch/index.js';
export * from './textprep/index.js';
export {
  generateDesignTokens,
  buildSlideHtml,
  generateBatch,
  validateSlide,
  DesignStage,
  runDesignStage,
  DesignAgentLoop,
  DESIGN_AGENT_TOOL_DEFINITIONS,
  runReactRefiner,
  createToolExecutor as createDesignToolExecutor,
  TOOL_SCHEMAS,
  ImageGenerator,
  fillImagePlaceholders,
  SVGGenerator,
  fillSvgPlaceholders,
  SlideSubAgent,
  VisualSubAgent,
  AssetRegistry,
  EditModeAgentLoop,
  EditModeTools,
  createEditToolExecutor,
  EditHistoryManager,
  DesignPhase,
  DESIGN_PHASE_TRANSITIONS,
  designPhaseMachine,
  DesignLoopStatus,
  DESIGN_LOOP_TRANSITIONS,
  designLoopMachine,
  SlideStatus,
  SLIDE_STATUS_TRANSITIONS,
  slideStatusMachine,
  VisualSlotStatus,
  VISUAL_SLOT_TRANSITIONS,
  visualSlotMachine,
  EditSessionStatus,
  EDIT_SESSION_TRANSITIONS,
  editSessionMachine,
  SubAgentStatus,
  SUB_AGENT_TRANSITIONS,
  subAgentMachine,
  ReviewStatus,
  REVIEW_TRANSITIONS,
  reviewMachine,
} from './design/index.js';
export {
  CodeSearchStage,
  CodeSearchState,
  runCodeSearchStage,
  registerCodeSearchStages,
  createToolExecutor as createCodeSearchToolExecutor,
  formatToolDefinitionsForLLM,
  TOOL_DEFINITIONS,
  CODESEARCH_SYSTEM_PROMPT,
  CODESEARCH_TODO_PLANNER_PROMPT,
  CODESEARCH_STEP_PROMPT,
  CODESEARCH_SUMMARIZE_PROMPT,
  PROMPTS,
  CodeSearchPhase,
  TodoStatus,
  isValidTodoStatus,
  isValidCodeSearchPhase,
} from './codesearch/index.js';
